### ISSUE TITLE
calf crashes sometimes when jack is freewheeling and/or has several xruns

### ISSUE THREAD

**Issue by synthnassizer** [calf-studio-gear/calf#146]
Hi there,
for reasons that are generally not related to calf, jack seems to have excessive timing errors and xruns every so often. The jackd shows in cli these error messages:

```
JackPosixSemaphore::TimedWait err = Connection timed out
JackFreewheelDriver::ProcessSync: SuspendRefNum error
JackAudioDriver::ProcessGraphSync: ProcessWriteSlaves error, engine may now behave abnormally!!
JackPosixSemaphore::TimedWait err = Connection timed out
JackAudioDriver::ProcessGraphSync: SuspendRefNum error, engine may now behave abnormally!!
```

I have many (5x) calf racks loaded at the time and sometimes some of them (but never all!) crash when the above message appears.

I run jack with 
`jackd -S -R -dalsa -C capture16 -P playback16 -r48000 -p256 -n2`

Other calfs (not the same everytime) and other jack clients (mpd, pulseaudio, zita-*,...) do not crash when this happens.  Should calf crash when this happens? Can they crashes be avoided somehow? 

Thank you in advance for your help

**Comment by synthnassizer** [comment]
not sure if this will be of any help, but I run calfjackhost(debug) through gdb. When the rack crashed , backtrace shows
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5cde941 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
(gdb) backtrace
#0  0x00007ffff5cde941 in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007ffff5cdef7b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007ffff5cdf30a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007ffff67ee447 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x00000000004212a1 in calf_plugins::gtk_session_environment::start_gui_loop (this=0x6d4c20) at gtk_session_env.cpp:41
#5  0x000000000043689c in main (argc=1, argv=0x7fffffffe4a8) at jackhost.cpp:568
```

is there some other info, I could provide that would be meaningful?

**Comment by synthnassizer** [comment]
further to this, I was running jackd with "-S" parameter (sync mode). Removing that, causes far LESS crashes of the opened calf racks. Hope this helps somehow.
